In [1]:
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],[2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],[3,4],[5,6]])
matMul = tf.matmul(data1,data2)#矩阵的标准乘法
matAdd = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))

[[24]]
[[8 8]
 [8 8]]


In [4]:
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],[2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],[3,4],[5,6]])
matMul = tf.matmul(data1,data2)
matMul2 = tf.multiply(data1,data2)#对应位置相乘 是错误 的
matAdd = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))
    print(sess.run(matMu12))#直接相乘 最高维度取极值 是错误的
    print(sess.run([matMul,matAdd]))

[[24]]
[[8 8]
 [8 8]]
[[12 12]
 [12 12]]
[array([[24]]), array([[8, 8],
       [8, 8]])]
