In [13]:
import numpy as np
data1 = np.array([1,2,3,4,5])
print(data1)
data2 = np.array([[1,2],[3,4]])
print(data2)
#维度
print(data1.shape,data2.shape)#打印维度
print(np.zeros([2,3]),np.ones([2,3]))#全一全零矩阵
data2[1,0] = 5
print(data2)#改
print(data2[1,1])#查
data3 = np.ones([2,3])
print(data3*2)
print(data3/3)
print(data3+2)
print(data3-1)
data4 = np.array([[1,2,3],[4,5,6]])
print(data4+data4)
print(data3*data4)#对应元素相乘

[1 2 3 4 5]
[[1 2]
 [3 4]]
(5,) (2, 2)
[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]]
[[1 2]
 [5 4]]
4
[[2. 2. 2.]
 [2. 2. 2.]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 2  4  6]
 [ 8 10 12]]
[[1. 2. 3.]
 [4. 5. 6.]]
